version: '3.4'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src:/var/www/app/src
    container_name: ecommerce-api
    expose:
      - '5000'
    ports:
      - '5000:5000'
    networks:
      - default
  