version: '3.4'

services:
  ecommercedb:
    image: mongo:7.0.2
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:example
    volumes:
      - ecommerce-mongodb:/data/db
    networks:
      - default
    expose:
      - '27017'
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/var/www/app/src
    container_name: api
    expose:
      - '5000'
    ports:
      - '5000:5000'
    networks:
      - default
    command: npm run dev

  

volumes:
  ecommerce-mongodb: